# Generated by Django 3.2.7 on 2021-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
