# Generated by Django 3.2.7 on 2021-09-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210905_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envcategory',
            options={'verbose_name_plural': 'Env categories'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill categories'},
        ),
    ]
