# Generated by Django 3.2.7 on 2021-09-26 14:00
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skill_category',
        ),
        migrations.AddField(
            model_name='product',
            name='skill_category',
            field=models.ManyToManyField(blank=True, null=True, to='products.SkillCategory'),
        ),
    ]
