# Generated by Django 3.2.7 on 2021-09-26 14:25
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210926_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skill_category',
            field=models.ManyToManyField(blank=True, to='products.SkillCategory'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='friendly_name',
            field=models.CharField(blank=True, default=[], max_length=254),
            preserve_default=False,
        ),
    ]
