# Generated by Django 3.2.7 on 2021-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_envcategory_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='env_category',
            field=models.ManyToManyField(to='products.EnvCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skill_category',
            field=models.ManyToManyField(to='products.SkillCategory'),
        ),
    ]
